
live_config_reload = true

[font]
size = 12.0

[font.bold]
family = "CaskaydiaCove Nerd Font"
style = "Heavy"

[font.bold_italic]
family = "CaskaydiaCove Nerd Font"
style = "Heavy Italic"

[font.italic]
family = "CaskaydiaCove Nerd Font"
style = "Medium Italic"

[font.normal]
family = "CaskaydiaCove Nerd Font"
style = "Medium"

[shell]
args = ['--login']
program = "/usr/bin/zsh"

[cursor]
style = "Beam"

[window]
startup_mode = "Windowed"
dynamic_padding = true
opacity = 1.0

[window.padding]
x = 6
y = 0

[window.dimensions]
columns = 90
lines = 30

[colors.normal]
black = "#21222c"
red = "#ff5555"
green = "#50fa7b"
yellow = "#f1fa8c"
blue = "#bd93f9"
magenta = "#ff79c6"
cyan = "#8be9fd"
white = "#f8f8f2"

[colors.primary]
background = "#282a36"
foreground = "#f8f8f2"

[colors.cursor]
text = "CellBackground"
cursor = "CellForeground"
